language: python

notifications:
  email: false

# Build on every branch push, tag push, and pull request change:
on: [push, pull_request]

jobs:
  include:
    - name: "Python 3.9 on Focal Linux"
      dist: focal
      python: 3.9           # this works for Linux but is ignored on macOS or Windows
      before_install:
        - sudo apt update
        - sudo apt install unrar
        - sudo apt install patool
    - name: "Python 3.9 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.9.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python39:/c/Python39/Scripts:$PATH
#    - name: "Python 3.8.0 on Xenial Linux"
#      dist: focal
#      python: 3.9


before_script:
  - pip install -U -r requirements.txt
  - pip install -U -r test_requirements.txt

script:
  - pytest --cov-config=.coveragerc --cov=bikit

after_success:
    - codecov # submit coverage

# deploy:
#   provider: pypi
#   user:
#     secure: YOUR_PYPI_USER_PUBLIC_SECRET_HERE
#   password:
#     secure: YOUR_PYPI_PASS_PUBLIC_SECRET_HERE
#   on:
#     tags: true
